# Root: Asteria-OS/Cargo.toml  (virtual workspace)
[workspace]
resolver = "2"
members = [
  "xtask",
  "boot",
  "kernel",
  "crates/hal",
  "crates/ui",
  "crates/hud",
  "crates/arch-x86_64"
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

